package WrapperDSL.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class CategoricalDistanceConditionalExpression_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append(SPropertyOperations.getEnum(ctx.getPrimaryInput(), PROPS.left$H7qt).toString());
    tgs.append(SPropertyOperations.getEnum(ctx.getPrimaryInput(), PROPS.operator$H7au).toString());
    tgs.append(SPropertyOperations.getEnum(ctx.getPrimaryInput(), PROPS.right$H7p0).toString());
  }

  private static final class PROPS {
    /*package*/ static final SProperty left$H7qt = MetaAdapterFactory.getProperty(0x3e1c68c4ebe640bdL, 0xa27fe74585aa2487L, 0x7970d3ea933febfdL, 0x7970d3ea933fec0cL, "left");
    /*package*/ static final SProperty operator$H7au = MetaAdapterFactory.getProperty(0x3e1c68c4ebe640bdL, 0xa27fe74585aa2487L, 0x7970d3ea933febfdL, 0x7970d3ea933fec00L, "operator");
    /*package*/ static final SProperty right$H7p0 = MetaAdapterFactory.getProperty(0x3e1c68c4ebe640bdL, 0xa27fe74585aa2487L, 0x7970d3ea933febfdL, 0x7970d3ea933fec09L, "right");
  }
}
