package WrapperDSL.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;

public class GPSSensorNormalLogicalExpression_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);

    String leftElementValue = SPropertyOperations.getString(((SNode) SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.leftElement$blNu)), PROPS.value$aI20);
    String newLeftElementValue = "TODO";

    if (leftElementValue.equals("Distance to Destiny")) {
      newLeftElementValue = "((Drone)thisJoinPoint.getArgs()[0]).getDistanceDestiny()";
    }

    tgs.append("(");
    tgs.append(newLeftElementValue);
    tgs.append(" ");
    tgs.appendNode(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.operator$74x8));
    tgs.append(" ");
    tgs.appendNode(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.rightElement$blOs));
    tgs.append(")");
    tgs.newLine();


  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink leftElement$blNu = MetaAdapterFactory.getContainmentLink(0x3c0688eb4e024d93L, 0x86be1d02f4019544L, 0xf8231681b95e20fL, 0x2bffada1898cef7eL, "leftElement");
    /*package*/ static final SContainmentLink operator$74x8 = MetaAdapterFactory.getContainmentLink(0x3c0688eb4e024d93L, 0x86be1d02f4019544L, 0x2bffada1898cefa7L, 0x2bffada1898d12f2L, "operator");
    /*package*/ static final SContainmentLink rightElement$blOs = MetaAdapterFactory.getContainmentLink(0x3c0688eb4e024d93L, 0x86be1d02f4019544L, 0xf8231681b95e20fL, 0x2bffada1898cef80L, "rightElement");
  }

  private static final class PROPS {
    /*package*/ static final SProperty value$aI20 = MetaAdapterFactory.getProperty(0x3c0688eb4e024d93L, 0x86be1d02f4019544L, 0x2bffada1898d13c7L, 0x2bffada1898d13c8L, "value");
  }
}
