package WrapperDSL.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public class OriginAndDestinationDistanceConditionalExpression_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append(SPropertyOperations.getEnum(ctx.getPrimaryInput(), PROPS.left$h0Hu).toString());
    tgs.append(SPropertyOperations.getEnum(ctx.getPrimaryInput(), PROPS.operator$h0Is).toString());
    tgs.appendNode(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.right1$h0U4));
  }

  private static final class PROPS {
    /*package*/ static final SProperty left$h0Hu = MetaAdapterFactory.getProperty(0x3e1c68c4ebe640bdL, 0xa27fe74585aa2487L, 0x72508e21f03ced43L, 0x72508e21f03ced46L, "left");
    /*package*/ static final SProperty operator$h0Is = MetaAdapterFactory.getProperty(0x3e1c68c4ebe640bdL, 0xa27fe74585aa2487L, 0x72508e21f03ced43L, 0x72508e21f03ced48L, "operator");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink right1$h0U4 = MetaAdapterFactory.getContainmentLink(0x3e1c68c4ebe640bdL, 0xa27fe74585aa2487L, 0x72508e21f03ced43L, 0x72508e21f03ced4bL, "right1");
  }
}
