package WrapperDSL.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class TurnCamera_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append("drone.setCameraState(CameraStateEnum.");
    tgs.append(SPropertyOperations.getEnum(ctx.getPrimaryInput(), PROPS.turn$Xdl0).toString().toUpperCase());
    tgs.append(");");
    tgs.newLine();
  }

  private static final class PROPS {
    /*package*/ static final SProperty turn$Xdl0 = MetaAdapterFactory.getProperty(0x3e1c68c4ebe640bdL, 0xa27fe74585aa2487L, 0x2132774545f609daL, 0x2132774545f609dbL, "turn");
  }
}
