package WrapperDSL.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.core.behavior.BaseConcept__BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class WindSensorNormalLogicalExpression_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    String rightElementValue = "";
    if (BaseConcept__BehaviorDescriptor.getPresentation_idhEwIMiw.invoke(((SNode) SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.rightElement$blOs))).equals("strong wind")) {
      rightElementValue = "((Drone)thisJoinPoint.getArgs()[0]).isStrongWind()";
    }
    tgs.append("(");
    tgs.appendNode(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.rightElement$blOs));
    tgs.append(")");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink rightElement$blOs = MetaAdapterFactory.getContainmentLink(0x3c0688eb4e024d93L, 0x86be1d02f4019544L, 0xf8231681b95e20fL, 0x2bffada1898cef80L, "rightElement");
  }
}
