package WrapperDSL.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_InaquelityConditionalOperator extends EnumerationDescriptorBase {

  public EnumerationDescriptor_InaquelityConditionalOperator() {
    super(0x3e1c68c4ebe640bdL, 0xa27fe74585aa2487L, 0x7970d3ea93340645L, "InaquelityConditionalOperator", "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/8750727080426341957");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_less_than_0 = new EnumerationDescriptor.MemberDescriptor("less_than", "<", 0x7970d3ea9334064aL, "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/8750727080426341962");
  private final EnumerationDescriptor.MemberDescriptor myMember_greater_than_0 = new EnumerationDescriptor.MemberDescriptor("greater_than", ">", 0x7970d3ea9334064bL, "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/8750727080426341963");
  private final EnumerationDescriptor.MemberDescriptor myMember_less_than_or_equal_to_0 = new EnumerationDescriptor.MemberDescriptor("less_than_or_equal_to", "<=", 0x7970d3ea9334064cL, "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/8750727080426341964");
  private final EnumerationDescriptor.MemberDescriptor myMember_greater_than_or_equal_to_0 = new EnumerationDescriptor.MemberDescriptor("greater_than_or_equal_to", ">=", 0x7970d3ea9334064dL, "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/8750727080426341965");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x3e1c68c4ebe640bdL, 0xa27fe74585aa2487L, 0x7970d3ea93340645L, 0x7970d3ea9334064aL, 0x7970d3ea9334064bL, 0x7970d3ea9334064cL, 0x7970d3ea9334064dL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_less_than_0, myMember_greater_than_0, myMember_less_than_or_equal_to_0, myMember_greater_than_or_equal_to_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "less_than":
        return myMember_less_than_0;
      case "greater_than":
        return myMember_greater_than_0;
      case "less_than_or_equal_to":
        return myMember_less_than_or_equal_to_0;
      case "greater_than_or_equal_to":
        return myMember_greater_than_or_equal_to_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
