package WrapperDSL.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_AxisEnum extends EnumerationDescriptorBase {

  public EnumerationDescriptor_AxisEnum() {
    super(0x3e1c68c4ebe640bdL, 0xa27fe74585aa2487L, 0x3004f1bb9b11a311L, "AxisEnum", "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/3460156201790186257");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_AxisX_0 = new EnumerationDescriptor.MemberDescriptor("AxisX", "x", 0x3004f1bb9b11a312L, "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/3460156201790186258");
  private final EnumerationDescriptor.MemberDescriptor myMember_AxisY_0 = new EnumerationDescriptor.MemberDescriptor("AxisY", "y", 0x3004f1bb9b11a313L, "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/3460156201790186259");
  private final EnumerationDescriptor.MemberDescriptor myMember_AxisZ_0 = new EnumerationDescriptor.MemberDescriptor("AxisZ", "z", 0x3004f1bb9b11a316L, "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/3460156201790186262");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x3e1c68c4ebe640bdL, 0xa27fe74585aa2487L, 0x3004f1bb9b11a311L, 0x3004f1bb9b11a312L, 0x3004f1bb9b11a313L, 0x3004f1bb9b11a316L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_AxisX_0, myMember_AxisY_0, myMember_AxisZ_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "AxisX":
        return myMember_AxisX_0;
      case "AxisY":
        return myMember_AxisY_0;
      case "AxisZ":
        return myMember_AxisZ_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
