package WrapperDSL.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_MissionStateGetEnum extends EnumerationDescriptorBase {

  public EnumerationDescriptor_MissionStateGetEnum() {
    super(0x3e1c68c4ebe640bdL, 0xa27fe74585aa2487L, 0x53e04e3aef1646bcL, "MissionStateGetEnum", "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/6043916714957489852");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_READY_TO_START_0 = new EnumerationDescriptor.MemberDescriptor("READY_TO_START", "READY TO START", 0x53e04e3aef1646bdL, "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/6043916714957489853");
  private final EnumerationDescriptor.MemberDescriptor myMember_READY_TO_UPLOAD_0 = new EnumerationDescriptor.MemberDescriptor("READY_TO_UPLOAD", "READY TO UPLOAD", 0x53e04e3aef1646beL, "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/6043916714957489854");
  private final EnumerationDescriptor.MemberDescriptor myMember_UPLOADING_0 = new EnumerationDescriptor.MemberDescriptor("UPLOADING", "UPLOADING", 0x53e04e3aef1646c1L, "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/6043916714957489857");
  private final EnumerationDescriptor.MemberDescriptor myMember_ERROR_0 = new EnumerationDescriptor.MemberDescriptor("ERROR", "ERROR", 0x53e04e3aef1646c5L, "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/6043916714957489861");
  private final EnumerationDescriptor.MemberDescriptor myMember_STARTED_0 = new EnumerationDescriptor.MemberDescriptor("STARTED", "STARTED", 0x53e04e3aef1646caL, "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/6043916714957489866");
  private final EnumerationDescriptor.MemberDescriptor myMember_PAUSED_0 = new EnumerationDescriptor.MemberDescriptor("PAUSED", "PAUSED", 0x53e04e3aef1646d0L, "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/6043916714957489872");
  private final EnumerationDescriptor.MemberDescriptor myMember_CANCELED_0 = new EnumerationDescriptor.MemberDescriptor("CANCELED", "CANCELED", 0x53e04e3aef1646d7L, "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/6043916714957489879");
  private final EnumerationDescriptor.MemberDescriptor myMember_RESUMED_0 = new EnumerationDescriptor.MemberDescriptor("RESUMED", "RESUMED", 0x53e04e3aef1646dfL, "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/6043916714957489887");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x3e1c68c4ebe640bdL, 0xa27fe74585aa2487L, 0x53e04e3aef1646bcL, 0x53e04e3aef1646bdL, 0x53e04e3aef1646beL, 0x53e04e3aef1646c1L, 0x53e04e3aef1646c5L, 0x53e04e3aef1646caL, 0x53e04e3aef1646d0L, 0x53e04e3aef1646d7L, 0x53e04e3aef1646dfL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_READY_TO_START_0, myMember_READY_TO_UPLOAD_0, myMember_UPLOADING_0, myMember_ERROR_0, myMember_STARTED_0, myMember_PAUSED_0, myMember_CANCELED_0, myMember_RESUMED_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "READY_TO_START":
        return myMember_READY_TO_START_0;
      case "READY_TO_UPLOAD":
        return myMember_READY_TO_UPLOAD_0;
      case "UPLOADING":
        return myMember_UPLOADING_0;
      case "ERROR":
        return myMember_ERROR_0;
      case "STARTED":
        return myMember_STARTED_0;
      case "PAUSED":
        return myMember_PAUSED_0;
      case "CANCELED":
        return myMember_CANCELED_0;
      case "RESUMED":
        return myMember_RESUMED_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
