package WrapperDSL.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_PayloadStateTriggerEventEnum extends EnumerationDescriptorBase {

  public EnumerationDescriptor_PayloadStateTriggerEventEnum() {
    super(0x3e1c68c4ebe640bdL, 0xa27fe74585aa2487L, 0x341ddc0f5796cc6aL, "PayloadStateTriggerEventEnum", "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/3755399622748982378");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_CANCELS_0 = new EnumerationDescriptor.MemberDescriptor("CANCELS", "CANCELS", 0x341ddc0f5796cc6bL, "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/3755399622748982379");
  private final EnumerationDescriptor.MemberDescriptor myMember_LOADS_0 = new EnumerationDescriptor.MemberDescriptor("LOADS", "LOADS", 0x341ddc0f5796cc6cL, "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/3755399622748982380");
  private final EnumerationDescriptor.MemberDescriptor myMember_UNLOADS_0 = new EnumerationDescriptor.MemberDescriptor("UNLOADS", "UNLOADS", 0x341ddc0f5796cc6fL, "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/3755399622748982383");
  private final EnumerationDescriptor.MemberDescriptor myMember_any_0 = new EnumerationDescriptor.MemberDescriptor("any", "*", 0x11de48ed5d7ee1d4L, "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/1287546727787586004");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x3e1c68c4ebe640bdL, 0xa27fe74585aa2487L, 0x341ddc0f5796cc6aL, 0x341ddc0f5796cc6bL, 0x341ddc0f5796cc6cL, 0x341ddc0f5796cc6fL, 0x11de48ed5d7ee1d4L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_CANCELS_0, myMember_LOADS_0, myMember_UNLOADS_0, myMember_any_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "CANCELS":
        return myMember_CANCELS_0;
      case "LOADS":
        return myMember_LOADS_0;
      case "UNLOADS":
        return myMember_UNLOADS_0;
      case "any":
        return myMember_any_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
