package WrapperDSL.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_ObstacleAvoidanceGetEnum extends EnumerationDescriptorBase {

  public EnumerationDescriptor_ObstacleAvoidanceGetEnum() {
    super(0x3e1c68c4ebe640bdL, 0xa27fe74585aa2487L, 0x53e04e3aef1648efL, "ObstacleAvoidanceGetEnum", "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/6043916714957490415");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_AUTO_LANDING_0 = new EnumerationDescriptor.MemberDescriptor("AUTO_LANDING", "AUTO LANDING", 0x53e04e3aef1648f0L, "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/6043916714957490416");
  private final EnumerationDescriptor.MemberDescriptor myMember_WAIT_0 = new EnumerationDescriptor.MemberDescriptor("WAIT", "WAIT", 0x53e04e3aef1648f1L, "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/6043916714957490417");
  private final EnumerationDescriptor.MemberDescriptor myMember_GO_HOME_0 = new EnumerationDescriptor.MemberDescriptor("GO_HOME", "GO HOME", 0x53e04e3aef1648f4L, "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/6043916714957490420");
  private final EnumerationDescriptor.MemberDescriptor myMember_ERROR_0 = new EnumerationDescriptor.MemberDescriptor("ERROR", "ERROR", 0x53e04e3aef1648f8L, "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/6043916714957490424");
  private final EnumerationDescriptor.MemberDescriptor myMember_ACTIVATED_0 = new EnumerationDescriptor.MemberDescriptor("ACTIVATED", "ACTIVATED", 0x53e04e3aef1648fdL, "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/6043916714957490429");
  private final EnumerationDescriptor.MemberDescriptor myMember_DEACTIVATED_0 = new EnumerationDescriptor.MemberDescriptor("DEACTIVATED", "DEACTIVATED", 0x53e04e3aef16490fL, "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/6043916714957490447");
  private final EnumerationDescriptor.MemberDescriptor myMember_DETECTED_0 = new EnumerationDescriptor.MemberDescriptor("DETECTED", "DETECTED", 0x53e04e3aef164916L, "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/6043916714957490454");
  private final EnumerationDescriptor.MemberDescriptor myMember_NON_DETECTED_0 = new EnumerationDescriptor.MemberDescriptor("NON_DETECTED", "NON-DETECTED", 0x53e04e3aef16491eL, "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/6043916714957490462");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x3e1c68c4ebe640bdL, 0xa27fe74585aa2487L, 0x53e04e3aef1648efL, 0x53e04e3aef1648f0L, 0x53e04e3aef1648f1L, 0x53e04e3aef1648f4L, 0x53e04e3aef1648f8L, 0x53e04e3aef1648fdL, 0x53e04e3aef16490fL, 0x53e04e3aef164916L, 0x53e04e3aef16491eL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_AUTO_LANDING_0, myMember_WAIT_0, myMember_GO_HOME_0, myMember_ERROR_0, myMember_ACTIVATED_0, myMember_DEACTIVATED_0, myMember_DETECTED_0, myMember_NON_DETECTED_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "AUTO_LANDING":
        return myMember_AUTO_LANDING_0;
      case "WAIT":
        return myMember_WAIT_0;
      case "GO_HOME":
        return myMember_GO_HOME_0;
      case "ERROR":
        return myMember_ERROR_0;
      case "ACTIVATED":
        return myMember_ACTIVATED_0;
      case "DEACTIVATED":
        return myMember_DEACTIVATED_0;
      case "DETECTED":
        return myMember_DETECTED_0;
      case "NON_DETECTED":
        return myMember_NON_DETECTED_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
