package WrapperDSL.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_CameraStateSetEnum extends EnumerationDescriptorBase {

  public EnumerationDescriptor_CameraStateSetEnum() {
    super(0x3e1c68c4ebe640bdL, 0xa27fe74585aa2487L, 0x53e04e3aef164852L, "CameraStateSetEnum", "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/6043916714957490258");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_START_0 = new EnumerationDescriptor.MemberDescriptor("START", "START", 0x53e04e3aef164853L, "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/6043916714957490259");
  private final EnumerationDescriptor.MemberDescriptor myMember_PAUSE_0 = new EnumerationDescriptor.MemberDescriptor("PAUSE", "PAUSE", 0x53e04e3aef164854L, "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/6043916714957490260");
  private final EnumerationDescriptor.MemberDescriptor myMember_STOP_0 = new EnumerationDescriptor.MemberDescriptor("STOP", "STOP", 0x53e04e3aef164857L, "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/6043916714957490263");
  private final EnumerationDescriptor.MemberDescriptor myMember_RESUME_0 = new EnumerationDescriptor.MemberDescriptor("RESUME", "RESUME", 0x53e04e3aef16485bL, "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/6043916714957490267");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x3e1c68c4ebe640bdL, 0xa27fe74585aa2487L, 0x53e04e3aef164852L, 0x53e04e3aef164853L, 0x53e04e3aef164854L, 0x53e04e3aef164857L, 0x53e04e3aef16485bL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_START_0, myMember_PAUSE_0, myMember_STOP_0, myMember_RESUME_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "START":
        return myMember_START_0;
      case "PAUSE":
        return myMember_PAUSE_0;
      case "STOP":
        return myMember_STOP_0;
      case "RESUME":
        return myMember_RESUME_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
