package WrapperDSL.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_PerformedOperationEnum extends EnumerationDescriptorBase {

  public EnumerationDescriptor_PerformedOperationEnum() {
    super(0x3e1c68c4ebe640bdL, 0xa27fe74585aa2487L, 0x76bf29ae47663f66L, "PerformedOperationEnum", "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/8556603645526163302");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_returnToHome_0 = new EnumerationDescriptor.MemberDescriptor("returnToHome", "Return to Home", 0x76bf29ae47663f67L, "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/8556603645526163303");
  private final EnumerationDescriptor.MemberDescriptor myMember_economicMode_0 = new EnumerationDescriptor.MemberDescriptor("economicMode", "Economic Mode", 0x76bf29ae47663f68L, "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/8556603645526163304");
  private final EnumerationDescriptor.MemberDescriptor myMember_safeLand_0 = new EnumerationDescriptor.MemberDescriptor("safeLand", "Safe Land", 0x76bf29ae47663f6bL, "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/8556603645526163307");
  private final EnumerationDescriptor.MemberDescriptor myMember_landing_0 = new EnumerationDescriptor.MemberDescriptor("landing", "Landing", 0x76bf29ae47663f6fL, "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/8556603645526163311");
  private final EnumerationDescriptor.MemberDescriptor myMember_TakeOff_0 = new EnumerationDescriptor.MemberDescriptor("TakeOff", "Takeoff", 0x76bf29ae47663f74L, "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/8556603645526163316");
  private final EnumerationDescriptor.MemberDescriptor myMember_manualControl_0 = new EnumerationDescriptor.MemberDescriptor("manualControl", "Manual Control", 0x76bf29ae47663f81L, "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/8556603645526163329");
  private final EnumerationDescriptor.MemberDescriptor myMember_mission_0 = new EnumerationDescriptor.MemberDescriptor("mission", "Mission", 0x76bf29ae47663f89L, "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/8556603645526163337");
  private final EnumerationDescriptor.MemberDescriptor myMember_rotation_0 = new EnumerationDescriptor.MemberDescriptor("rotation", "Rotation", 0x76bf29ae47663f7aL, "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/8556603645526163322");
  private final EnumerationDescriptor.MemberDescriptor myMember_maneuver_0 = new EnumerationDescriptor.MemberDescriptor("maneuver", "Maneuver", 0x76bf29ae47663f92L, "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/8556603645526163346");
  private final EnumerationDescriptor.MemberDescriptor myMember_gambial_movement_0 = new EnumerationDescriptor.MemberDescriptor("gambial_movement", "Gambial Moviment", 0x76bf29ae47663f9cL, "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/8556603645526163356");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x3e1c68c4ebe640bdL, 0xa27fe74585aa2487L, 0x76bf29ae47663f66L, 0x76bf29ae47663f67L, 0x76bf29ae47663f68L, 0x76bf29ae47663f6bL, 0x76bf29ae47663f6fL, 0x76bf29ae47663f74L, 0x76bf29ae47663f81L, 0x76bf29ae47663f89L, 0x76bf29ae47663f7aL, 0x76bf29ae47663f92L, 0x76bf29ae47663f9cL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_returnToHome_0, myMember_economicMode_0, myMember_safeLand_0, myMember_landing_0, myMember_TakeOff_0, myMember_manualControl_0, myMember_mission_0, myMember_rotation_0, myMember_maneuver_0, myMember_gambial_movement_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "returnToHome":
        return myMember_returnToHome_0;
      case "economicMode":
        return myMember_economicMode_0;
      case "safeLand":
        return myMember_safeLand_0;
      case "landing":
        return myMember_landing_0;
      case "TakeOff":
        return myMember_TakeOff_0;
      case "manualControl":
        return myMember_manualControl_0;
      case "mission":
        return myMember_mission_0;
      case "rotation":
        return myMember_rotation_0;
      case "maneuver":
        return myMember_maneuver_0;
      case "gambial_movement":
        return myMember_gambial_movement_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
