package WrapperDSL.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_GeneralOperatorEnum extends EnumerationDescriptorBase {

  public EnumerationDescriptor_GeneralOperatorEnum() {
    super(0x3e1c68c4ebe640bdL, 0xa27fe74585aa2487L, 0x53e04e3aef1642fcL, "GeneralOperatorEnum", "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/6043916714957488892");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_iqual_0 = new EnumerationDescriptor.MemberDescriptor("iqual", "==", 0x53e04e3aef1642feL, "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/6043916714957488894");
  private final EnumerationDescriptor.MemberDescriptor myMember_not_equal_0 = new EnumerationDescriptor.MemberDescriptor("not_equal", "≠", 0x53e04e3aef1642ffL, "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/6043916714957488895");
  private final EnumerationDescriptor.MemberDescriptor myMember_greater_than_0 = new EnumerationDescriptor.MemberDescriptor("greater_than", ">", 0x53e04e3aef16430fL, "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/6043916714957488911");
  private final EnumerationDescriptor.MemberDescriptor myMember_less_than_0 = new EnumerationDescriptor.MemberDescriptor("less_than", "<", 0x53e04e3aef164310L, "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/6043916714957488912");
  private final EnumerationDescriptor.MemberDescriptor myMember_greater_than_or_equal_to_0 = new EnumerationDescriptor.MemberDescriptor("greater_than_or_equal_to", "≥", 0x53e04e3aef164311L, "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/6043916714957488913");
  private final EnumerationDescriptor.MemberDescriptor myMember_less_than_or_equal_to_0 = new EnumerationDescriptor.MemberDescriptor("less_than_or_equal_to", "≤", 0x53e04e3aef164312L, "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/6043916714957488914");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x3e1c68c4ebe640bdL, 0xa27fe74585aa2487L, 0x53e04e3aef1642fcL, 0x53e04e3aef1642feL, 0x53e04e3aef1642ffL, 0x53e04e3aef16430fL, 0x53e04e3aef164310L, 0x53e04e3aef164311L, 0x53e04e3aef164312L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_iqual_0, myMember_not_equal_0, myMember_greater_than_0, myMember_less_than_0, myMember_greater_than_or_equal_to_0, myMember_less_than_or_equal_to_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "iqual":
        return myMember_iqual_0;
      case "not_equal":
        return myMember_not_equal_0;
      case "greater_than":
        return myMember_greater_than_0;
      case "less_than":
        return myMember_less_than_0;
      case "greater_than_or_equal_to":
        return myMember_greater_than_or_equal_to_0;
      case "less_than_or_equal_to":
        return myMember_less_than_or_equal_to_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
