package WrapperDSL.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_GPSResultEnum extends EnumerationDescriptorBase {

  public EnumerationDescriptor_GPSResultEnum() {
    super(0x3e1c68c4ebe640bdL, 0xa27fe74585aa2487L, 0x7fd8262c2025d6e3L, "GPSResultEnum", "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/9212155008746116835");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_STRONG_SIGNAL_0 = new EnumerationDescriptor.MemberDescriptor("STRONG_SIGNAL", "STRONG SIGNAL", 0x7fd8262c2025d6e5L, "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/9212155008746116837");
  private final EnumerationDescriptor.MemberDescriptor myMember_WEAK_SIGNAL_0 = new EnumerationDescriptor.MemberDescriptor("WEAK_SIGNAL", "WEAK SIGNAL", 0x7fd8262c2025d6f0L, "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/9212155008746116848");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x3e1c68c4ebe640bdL, 0xa27fe74585aa2487L, 0x7fd8262c2025d6e3L, 0x7fd8262c2025d6e5L, 0x7fd8262c2025d6f0L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_STRONG_SIGNAL_0, myMember_WEAK_SIGNAL_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "STRONG_SIGNAL":
        return myMember_STRONG_SIGNAL_0;
      case "WEAK_SIGNAL":
        return myMember_WEAK_SIGNAL_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
