package WrapperDSL.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_RelativePositionEnum extends EnumerationDescriptorBase {

  public EnumerationDescriptor_RelativePositionEnum() {
    super(0x3e1c68c4ebe640bdL, 0xa27fe74585aa2487L, 0x7970d3ea933fec04L, "RelativePositionEnum", "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/8750727080427121668");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_OBSTACLE_0 = new EnumerationDescriptor.MemberDescriptor("OBSTACLE", "OBSTACLE", 0x7970d3ea933fec06L, "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/8750727080427121670");
  private final EnumerationDescriptor.MemberDescriptor myMember_DESTINATION_0 = new EnumerationDescriptor.MemberDescriptor("DESTINATION", "DESTINATION", 0x7970d3ea933fec05L, "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/8750727080427121669");
  private final EnumerationDescriptor.MemberDescriptor myMember_ORIGIN_0 = new EnumerationDescriptor.MemberDescriptor("ORIGIN", "ORIGIN", 0x53e04e3aef1646adL, "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/6043916714957489837");
  private final EnumerationDescriptor.MemberDescriptor myMember_WATER_0 = new EnumerationDescriptor.MemberDescriptor("WATER", "WATER", 0x53e04e3aef1646b1L, "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/6043916714957489841");
  private final EnumerationDescriptor.MemberDescriptor myMember_LAND_0 = new EnumerationDescriptor.MemberDescriptor("LAND", "LAND", 0x53e04e3aef1646b6L, "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/6043916714957489846");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x3e1c68c4ebe640bdL, 0xa27fe74585aa2487L, 0x7970d3ea933fec04L, 0x7970d3ea933fec06L, 0x7970d3ea933fec05L, 0x53e04e3aef1646adL, 0x53e04e3aef1646b1L, 0x53e04e3aef1646b6L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_OBSTACLE_0, myMember_DESTINATION_0, myMember_ORIGIN_0, myMember_WATER_0, myMember_LAND_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "OBSTACLE":
        return myMember_OBSTACLE_0;
      case "DESTINATION":
        return myMember_DESTINATION_0;
      case "ORIGIN":
        return myMember_ORIGIN_0;
      case "WATER":
        return myMember_WATER_0;
      case "LAND":
        return myMember_LAND_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
