package WrapperDSL.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_SmokerDetectorTriggerEventEnum extends EnumerationDescriptorBase {

  public EnumerationDescriptor_SmokerDetectorTriggerEventEnum() {
    super(0x3e1c68c4ebe640bdL, 0xa27fe74585aa2487L, 0x11de48ed5d7ee1e7L, "SmokerDetectorTriggerEventEnum", "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/1287546727787586023");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_CALIBRATES_0 = new EnumerationDescriptor.MemberDescriptor("CALIBRATES", "CALIBRATES", 0x11de48ed5d7ee1edL, "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/1287546727787586029");
  private final EnumerationDescriptor.MemberDescriptor myMember_ACTIVATES_0 = new EnumerationDescriptor.MemberDescriptor("ACTIVATES", "ACTIVATES", 0x11de48ed5d7ee1eeL, "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/1287546727787586030");
  private final EnumerationDescriptor.MemberDescriptor myMember_DEACTIVATES_0 = new EnumerationDescriptor.MemberDescriptor("DEACTIVATES", "DEACTIVATES", 0x11de48ed5d7ee1efL, "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/1287546727787586031");
  private final EnumerationDescriptor.MemberDescriptor myMember_any_0 = new EnumerationDescriptor.MemberDescriptor("any", "*", 0x11de48ed5d7ee21dL, "r:791815a7-51ee-4ec9-bcc3-2de9ba0316d3(WrapperDSL.structure)/1287546727787586077");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x3e1c68c4ebe640bdL, 0xa27fe74585aa2487L, 0x11de48ed5d7ee1e7L, 0x11de48ed5d7ee1edL, 0x11de48ed5d7ee1eeL, 0x11de48ed5d7ee1efL, 0x11de48ed5d7ee21dL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_CALIBRATES_0, myMember_ACTIVATES_0, myMember_DEACTIVATES_0, myMember_any_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "CALIBRATES":
        return myMember_CALIBRATES_0;
      case "ACTIVATES":
        return myMember_ACTIVATES_0;
      case "DEACTIVATES":
        return myMember_DEACTIVATES_0;
      case "any":
        return myMember_any_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
