package WrapperDSL.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int AdviseScript = 0;
  public static final int AltitudeConditionalExpression = 1;
  public static final int AngularAccelerationConditionalExpression = 2;
  public static final int BatteryConditionalExpression = 3;
  public static final int CameraPowerConditionalExtension = 4;
  public static final int CancelGoHome = 5;
  public static final int CancelLanding = 6;
  public static final int CancelTakeOff = 7;
  public static final int CategoricalDistanceConditionalExpression = 8;
  public static final int CategoricalWindConditionalExpression = 9;
  public static final int Command = 10;
  public static final int CompassConditionalExpression = 11;
  public static final int ConditionalExpression = 12;
  public static final int ConfirmLanding = 13;
  public static final int ConjunctionLogicalExpression = 14;
  public static final int CoordenateConditionalExpression = 15;
  public static final int DisjunctionLogicalExpression = 16;
  public static final int ExceptionalScenario = 17;
  public static final int Expression = 18;
  public static final int GimbalConditionalExtension = 19;
  public static final int Given = 20;
  public static final int If = 21;
  public static final int LandingGearConditionalExtension = 22;
  public static final int LinearAccelerationConditionalExtension = 23;
  public static final int LogicalExpression = 24;
  public static final int MathElement = 25;
  public static final int MotorsPowerConditionalExtension = 26;
  public static final int OriginAndDestinationDistanceConditionalExpression = 27;
  public static final int PauseMission = 28;
  public static final int PayloadConditionalExtension = 29;
  public static final int PointCut = 30;
  public static final int RegionConditionalExpression = 31;
  public static final int ResumeMission = 32;
  public static final int ScalarDistanceConditionalExpression = 33;
  public static final int ScalarWindConditionalExpression = 34;
  public static final int SetAutoFlightSpeed = 35;
  public static final int SetGoHomeHeightInMeters = 36;
  public static final int SetHomeLocation = 37;
  public static final int SetHomeLocationUsingAircraftCurrentLocation = 38;
  public static final int SetLowBatteryWarningThreshold = 39;
  public static final int SetSeriousLowBatteryWarningThreshold = 40;
  public static final int SetSmartReturnToHomeEnabled = 41;
  public static final int SpeedConditionalExpression = 42;
  public static final int StartGoHome = 43;
  public static final int StartLanding = 44;
  public static final int StartMission = 45;
  public static final int StartPrecisionTakeOff = 46;
  public static final int StartTakeOff = 47;
  public static final int Statement = 48;
  public static final int Text = 49;
  public static final int Then = 50;
  public static final int TurnOffMotors = 51;
  public static final int TurnOnMotors = 52;
  public static final int UAVCommand = 53;
  public static final int Value = 54;
  public static final int When = 55;
  public static final int While = 56;
  public static final int WifiConditionalExtension = 57;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x3e1c68c4ebe640bdL, 0xa27fe74585aa2487L);
    builder.put(0x53be3ecc046e0b54L, AdviseScript);
    builder.put(0x1053550ed8ac3a37L, AltitudeConditionalExpression);
    builder.put(0x1e50d2b0bcf0f56aL, AngularAccelerationConditionalExpression);
    builder.put(0x53be3ecc04699240L, BatteryConditionalExpression);
    builder.put(0x1053550ed8b71613L, CameraPowerConditionalExtension);
    builder.put(0x6e9fd935895a9525L, CancelGoHome);
    builder.put(0x6e9fd935895a94d4L, CancelLanding);
    builder.put(0x6e9fd9358959647dL, CancelTakeOff);
    builder.put(0x7970d3ea933febfdL, CategoricalDistanceConditionalExpression);
    builder.put(0x53be3ecc045a8cddL, CategoricalWindConditionalExpression);
    builder.put(0x53be3ecc047dcb4aL, Command);
    builder.put(0x3f0a90391eda7f7L, CompassConditionalExpression);
    builder.put(0x7970d3ea932a97ffL, ConditionalExpression);
    builder.put(0x6e9fd935895a94efL, ConfirmLanding);
    builder.put(0x53be3ecc045a8c9bL, ConjunctionLogicalExpression);
    builder.put(0x53be3ecc045a8ce3L, CoordenateConditionalExpression);
    builder.put(0x53be3ecc045a8c9cL, DisjunctionLogicalExpression);
    builder.put(0x53be3ecc045a8bc3L, ExceptionalScenario);
    builder.put(0x7970d3ea932ed73dL, Expression);
    builder.put(0x1053550ed8b71646L, GimbalConditionalExtension);
    builder.put(0x53be3ecc045a8bcaL, Given);
    builder.put(0x53be3ecc045b45abL, If);
    builder.put(0x1053550ed8b3fbfaL, LandingGearConditionalExtension);
    builder.put(0x3004f1bb9b15123cL, LinearAccelerationConditionalExtension);
    builder.put(0x7970d3ea932a97fbL, LogicalExpression);
    builder.put(0x53be3ecc045a8bd6L, MathElement);
    builder.put(0x1053550ed8b2a0a3L, MotorsPowerConditionalExtension);
    builder.put(0x72508e21f03ced43L, OriginAndDestinationDistanceConditionalExpression);
    builder.put(0x6e9fd935895bcb96L, PauseMission);
    builder.put(0x1053550ed8b3fc74L, PayloadConditionalExtension);
    builder.put(0x53be3ecc046e0b59L, PointCut);
    builder.put(0x53be3ecc045a8ce0L, RegionConditionalExpression);
    builder.put(0x6e9fd935895bcbb1L, ResumeMission);
    builder.put(0x53be3ecc048c5944L, ScalarDistanceConditionalExpression);
    builder.put(0x7970d3ea93368919L, ScalarWindConditionalExpression);
    builder.put(0x6e9fd935895bcbe8L, SetAutoFlightSpeed);
    builder.put(0x6e9fd935895a955bL, SetGoHomeHeightInMeters);
    builder.put(0x6e9fd93589583f6bL, SetHomeLocation);
    builder.put(0x6e9fd935895a9540L, SetHomeLocationUsingAircraftCurrentLocation);
    builder.put(0x6e9fd935895bcacfL, SetLowBatteryWarningThreshold);
    builder.put(0x6e9fd935895bcb00L, SetSeriousLowBatteryWarningThreshold);
    builder.put(0x6e9fd935895bcb3cL, SetSmartReturnToHomeEnabled);
    builder.put(0x3f0a90391ea8938L, SpeedConditionalExpression);
    builder.put(0x6e9fd935895a950aL, StartGoHome);
    builder.put(0x6e9fd93589596498L, StartLanding);
    builder.put(0x6e9fd935895bcb74L, StartMission);
    builder.put(0x6e9fd93589596462L, StartPrecisionTakeOff);
    builder.put(0x6e9fd93589596447L, StartTakeOff);
    builder.put(0x53be3ecc045b453cL, Statement);
    builder.put(0x53be3ecc0462d3feL, Text);
    builder.put(0x53be3ecc045a8bccL, Then);
    builder.put(0x6e9fd93589596429L, TurnOffMotors);
    builder.put(0x6e9fd9358959640bL, TurnOnMotors);
    builder.put(0x6e9fd9358955fd28L, UAVCommand);
    builder.put(0x53be3ecc0462d3fbL, Value);
    builder.put(0x53be3ecc045a8bcbL, When);
    builder.put(0x53be3ecc045b45acL, While);
    builder.put(0x1053550ed8b3fc39L, WifiConditionalExtension);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
